default:
  image: node:18

install_package:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
      - dist

publish_package:
  stage: deploy
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - npm publish --verbose
  rules:
    - if: $CI_COMMIT_TAG =~ /v\d+\.\d+\.\d+/

release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /v\d+\.\d+\.\d+/
  script:
    - echo "Creating release"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'